apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsbl-config
  namespace: postal
data:
  # Database (non-sensitive)
  DB_HOST: "postgresql.postal.svc.cluster.local"
  DB_PORT: "5432"
  DB_NAME: "postal"
  DB_USER: "dnsbl_monitor"
  
  # DNSBL zones (comma-separated)
  DNSBL_ZONES: "0spam.fusionzero.com,access.redhawk.org,all.rbl.jp,all.s5h.net,all.spamrats.com,b.barracudacentral.org,bl.blocklist.de,bl.emailbasura.org,bl.mailspike.org,bl.score.senderscore.com,bl.spamcannibal.org,bl.spamcop.net,bl.spameatingmonkey.net,bogons.cymru.com,cblplus.anti-spam.org.cn,cidr.bl.mcafee.com,combined.njabl.org,db.wpbl.info,dnsbl-1.uceprotect.net,dnsbl-2.uceprotect.net,dnsbl-3.uceprotect.net,dnsbl.ahbl.org,dnsbl.burnt-tech.com,dnsbl.dronebl.org,dnsbl.inps.de,dnsbl.justspam.org,dnsbl.kempt.net,dnsbl.rv-soft.info,dnsbl.solid.net,dnsbl.sorbs.net,dnsbl.tornevall.org,dnsbl.webequipped.com,dnsrbl.swinog.ch,fnrbl.fast.net,ip.v4bl.org,ips.backscatterer.org,ix.dnsbl.manitu.net,korea.services.net,l2.apews.org,l2.bbfh.ext.sorbs.net,list.blogspambl.com,lookup.dnsbl.iip.lu,mail-abuse.blacklist.jippg.org,psbl.surriel.com,rbl2.triumf.ca,rbl.choon.net,rbl.dns-servicios.com,rbl.efnetrbl.org,rbl.orbitrbl.com,rbl.polarcomm.net,singlebl.spamgrouper.com,spam.abuse.ch,spam.dnsbl.sorbs.net,spam.pedantic.org,spamguard.leadmon.net,spamrbl.imp.ch,spamsources.fabel.dk,spamtrap.trblspam.com,st.technovision.dk,tor.dan.me.uk,tor.dnsbl.sectoor.de,truncate.gbudb.net,ubl.unsubscore.com,virbl.dnsbl.bit.nl,work.drbl.gremlin.ru,zen.spamhaus.org,backscatter.spameatingmonkey.net,bl.drmx.org,bl.nosolicitado.org,bl.scientificspam.net,bl.worst.nosolicitado.org,black.mail.abusix.zone,cbl.abuseat.org,dnsbl.spfbl.net,dnsbl.zapbl.net,dyna.spamrats.com,invaluement SIP,NordSpam,netscan.rbl.blockedservers.com,pbl.spamhaus.org,rbl.abuse.ro,sbl.spamhaus.org,spam.spamrats.com,mail-abuse.com,torexit.dan.me.uk,xbl.spamhaus.org,bb.barracudacentral.org,bl.mailspike.net,bl.rbl.scrolloutf1.com,bl.suomispam.net,black.junkemailfilter.com,cart00ney.surriel.com,dnsbl.net.ua,exploit.mail.abusix.zone,hostkarma.junkemailfilter.com,invaluement SIP/24,multi.surbl.org,noptr.spamrats.com,rbl.blockedservers.com,rbl.interserver.net,rep.mailspike.net,spam.dnsbl.anonmails.de,spam.rbl.blockedservers.com,spamlist.or.kr,talosintelligence.com,z.mailspike.net"
  DNS_TIMEOUT: "5"
  DNS_CONCURRENCY: "10"
  
  # Priorities
  LISTED_PRIORITY: "9"
  CLEAN_FALLBACK_PRIORITY: "100"
  
  # Jira (non-sensitive)
  JIRA_SERVER: "https://modalsource.atlassian.net"
  JIRA_USER: "dnsbl-bot@company.com"
  JIRA_PROJECT: "OPS"
  JIRA_ISSUE_TYPE: "Incident"
  JIRA_DNS_FAILURE_ISSUE_TYPE: "Alert"
  JIRA_EXCLUDED_STATUSES: "Done,Closed,Resolved"
  
  # Operational
  DRY_RUN: "true"
